#ifndef SKAN_CORE_CONSTANTS_H
#define SKAN_CORE_CONSTANTS_H

#define SKAN_VERSION "0.1.0"

#define SKAN_MAX_HOSTNAME_LENGTH 256U
#define SKAN_MAX_SERVICE_NAME_LENGTH 64U

#define SKAN_PROTOCOL_NUMBER_TCP 6U
#define SKAN_PROTOCOL_NUMBER_UDP 17U

#define SKAN_PHASE0_DEFAULT_FIRST_PORT 0U
#define SKAN_PHASE0_DEFAULT_LAST_PORT 0U

#endif /* SKAN_CORE_CONSTANTS_H */
