#include <cassert>
#include <array>
#include <charconv>
#include <algorithm>
#include <iostream>

#include "io/io_engine.hpp"
#include "net/interface.hpp"
#include "net/network_scan_transport.hpp"
#include "packet/packet.hpp"
#include "packet/checksum.hpp"
#include "portscan/tcp_syn.hpp"

namespace {

void assert_syn_assessment(const skan::portscan::PortSubmission &submission,
                           const std::vector<std::uint8_t> &bytes,
                           skan::portscan::PortState expected_state,
                           skan::portscan::ScanReason expected_reason)
{
    using namespace skan;
    portscan::PortResponse response;
    response.id = submission.id;
    response.source_ip = submission.target_ip;
    response.kind = portscan::PortResponseKind::Packet;
    response.bytes = bytes;
    auto state = portscan::PortState::Unknown;
    auto reason = portscan::ScanReason::InternalError;
    portscan::TcpSynProbe probe;
    assert(probe.assess(response, submission, state, reason) == core::StatusCode::Ok);
    assert(state == expected_state && reason == expected_reason);
    auto wrong_id = response; ++wrong_id.id;
    assert(probe.assess(wrong_id, submission, state, reason) == core::StatusCode::NotFound);
}

void test_captured_open_and_closed_syn_responses()
{
    using namespace skan;
    struct CapturedReply {
        std::string_view frame;
        std::uint16_t remote_port;
        std::uint16_t local_port;
        std::uint32_t sent_sequence;
    };
    // Literal independent CORE-01 wire evidence, not generated by Skan's builders.
    const CapturedReply cases[] = {
        {"8a35fe6f73839e429e2cf58008004500002c000040004006b6c0c0000206c0000205"
         "46a09c41ba9238e642b771b86012faf08e4f0000020405b4", 18080U, 40001U, 1119318455U},
        {"8a35fe6f73839e429e2cf580080045000028000040004006b6c4c0000206c0000205"
         "46a29c42000000004303a3df5014000061fd0000", 18082U, 40002U, 1124312030U},
    };
    for (const auto &captured : cases) {
        std::vector<std::uint8_t> frame;
        for (std::size_t offset = 0; offset < captured.frame.size(); offset += 2U) {
            unsigned int byte = 0U;
            const char *first = captured.frame.data() + offset;
            const auto parsed = std::from_chars(first, first + 2, byte, 16);
            assert(parsed.ec == std::errc{} && parsed.ptr == first + 2);
            frame.push_back(static_cast<std::uint8_t>(byte));
        }
        const auto reply = net::PacketReceiver::parse(frame);
        assert(reply.valid() && reply.ipv4 && reply.tcp);
        portscan::PortSubmission submission;
        submission.id = 42U;
        submission.probe = portscan::ScanProbeType::TcpSyn;
        submission.source_ip = core::IpAddress::from_ipv4(0xc0000205U);
        submission.target_ip = core::IpAddress::from_ipv4(0xc0000206U);
        submission.source_port = captured.local_port;
        submission.port = {captured.remote_port, portscan::Protocol::Tcp};
        submission.sequence_number = captured.sent_sequence;
        assert(net::matches_tcp_reply(submission, reply));
        net::CorrelationTable table;
        const net::CorrelationKey sent{0xc0000206U, captured.local_port, captured.remote_port,
                                      captured.sent_sequence, submission.target_ip};
        const net::CorrelationKey received{reply.ipv4->source_address(), reply.tcp->destination_port(),
            reply.tcp->source_port(), reply.tcp->acknowledgment_number() - 1U,
            core::IpAddress::from_ipv4(reply.ipv4->source_address())};
        assert(table.insert(sent, 42U, std::chrono::steady_clock::time_point::max()) == net::CorrelationStatus::Inserted);
        const auto found = table.lookup(received, std::chrono::steady_clock::now());
        assert(found.status == net::CorrelationStatus::Found && found.entry->token == 42U);
        const auto bytes = net::tcp_response_bytes(reply);
        assert(bytes && std::equal(bytes->begin(), bytes->end(), frame.begin() + 34));
        const bool closed = captured.remote_port == 18082U;
        assert_syn_assessment(submission, *bytes,
            closed ? portscan::PortState::Closed : portscan::PortState::Open,
            closed ? portscan::ScanReason::Rst : portscan::ScanReason::SynAck);
        auto wrong_ack = submission; ++wrong_ack.sequence_number;
        assert(!net::matches_tcp_reply(wrong_ack, reply));
        auto wrong_destination = submission; wrong_destination.source_ip.bytes[3] = 7U;
        assert(!net::matches_tcp_reply(wrong_destination, reply));
        assert(table.remove(sent) == net::CorrelationStatus::Removed);
        assert(table.lookup(received, std::chrono::steady_clock::now()).status == net::CorrelationStatus::NotFound);
    }
}

void test_tcp_response_preserves_valid_wire_options()
{
    using namespace skan;
    // A model that discards unknown options or EOL padding cannot reconstruct
    // this validated wire header. Losing it must not manufacture a timeout.
    for (const bool ipv6 : {false, true}) {
        for (const auto options : {std::array<std::uint8_t, 4U>{0xfeU, 4U, 0x12U, 0x34U},
                                   std::array<std::uint8_t, 4U>{0U, 0U, 0U, 0U},
                                   std::array<std::uint8_t, 4U>{2U, 4U, 5U, 0xb4U}}) {
            const auto local = *core::parse_ip_address(ipv6 ? "2001:db8::1" : "192.0.2.5");
            const auto remote = *core::parse_ip_address(ipv6 ? "2001:db8::2" : "192.0.2.6");
            packet::Packet reply;
            reply.set_ethernet(packet::Ethernet({}, {}, ipv6 ? 0x86ddU : 0x0800U));
            if (ipv6) {
                packet::IPv6 ip; ip.set_next_header(6U);
                ip.set_source_address(remote.bytes); ip.set_destination_address(local.bytes); reply.set_ipv6(ip);
            } else {
                packet::IPv4 ip; ip.set_protocol(6U);
                ip.set_source_address(0xc0000206U); ip.set_destination_address(0xc0000205U); reply.set_ipv4(ip);
            }
            packet::TCP tcp;
            tcp.set_source_port(18080U); tcp.set_destination_port(40001U);
            tcp.set_sequence_number(3130144998U); tcp.set_acknowledgment_number(1119318456U);
            tcp.set_flags(packet::TcpFlag::Syn | packet::TcpFlag::Ack); reply.set_tcp(tcp);
            auto frame = reply.serialize();
            const std::size_t ip_offset = 14U;
            const std::size_t tcp_offset = ip_offset + (ipv6 ? 40U : 20U);
            frame.insert(frame.end(), options.begin(), options.end());
            frame[tcp_offset + 12U] = 0x60U;
            packet::wire::write_u16(frame, tcp_offset + 16U, 0U);
            if (ipv6) { packet::wire::write_u16(frame, ip_offset + 4U, 24U); }
            else {
                packet::wire::write_u16(frame, ip_offset + 2U, 44U);
                packet::wire::write_u16(frame, ip_offset + 10U, 0U);
                packet::wire::write_u16(frame, ip_offset + 10U,
                    packet::checksum::internet(std::span<const std::uint8_t>{frame}.subspan(ip_offset, 20U)));
            }
            const auto wire = std::span<const std::uint8_t>{frame}.subspan(tcp_offset, 24U);
            const auto sum = ipv6 ? packet::checksum::ipv6_pseudo_header(remote.bytes, local.bytes, 6U, wire)
                                 : packet::checksum::ipv4_pseudo_header(0xc0000206U, 0xc0000205U, 6U, wire);
            packet::wire::write_u16(frame, tcp_offset + 16U, sum);
            const auto parsed = net::PacketReceiver::parse(frame);
            assert(parsed.valid());
            portscan::PortSubmission submission;
            submission.id = 42U;
            submission.probe = portscan::ScanProbeType::TcpSyn;
            submission.source_ip = local; submission.target_ip = remote;
            submission.source_port = 40001U; submission.port = {18080U, portscan::Protocol::Tcp};
            submission.sequence_number = 1119318455U;
            assert(net::matches_tcp_reply(submission, parsed));
            const auto bytes = net::tcp_response_bytes(parsed);
            assert(bytes.has_value());
            assert(bytes->size() == 24U);
            assert(std::equal(bytes->begin(), bytes->end(), frame.begin() + static_cast<std::ptrdiff_t>(tcp_offset)));
            const auto preserved = packet::TCP::parse(*bytes);
            assert(preserved && preserved->acknowledgment_number() == 1119318456U);
            assert_syn_assessment(submission, *bytes, portscan::PortState::Open, portscan::ScanReason::SynAck);
            auto wrong_ack = submission; ++wrong_ack.sequence_number;
            assert(!net::matches_tcp_reply(wrong_ack, parsed));
            auto invalid = parsed; invalid.status = net::ParseStatus::MalformedTCP;
            assert(!net::tcp_response_bytes(invalid));
            invalid = parsed; invalid.raw_frame.resize(tcp_offset + 23U);
            assert(!net::tcp_response_bytes(invalid));
            invalid = parsed; invalid.raw_frame.clear();
            assert(!net::tcp_response_bytes(invalid));
            auto bad_checksum = frame; bad_checksum[tcp_offset + 16U] ^= 1U;
            assert(!net::PacketReceiver::parse(bad_checksum).valid());
            auto tagged = frame;
            tagged.insert(tagged.begin() + 12, {0x81U, 0U, 0U, 7U});
            const auto vlan = net::PacketReceiver::parse(tagged);
            assert(vlan.valid());
            assert(net::tcp_response_bytes(vlan) == bytes);
            auto padded = tagged;
            padded.insert(padded.end(), 16U, 0xa5U); // Ethernet padding is not TCP payload.
            const auto padding = net::PacketReceiver::parse(padded);
            assert(padding.valid());
            assert(net::tcp_response_bytes(padding) == bytes);
            if (ipv6) {
                auto extended = frame;
                extended.insert(extended.begin() + static_cast<std::ptrdiff_t>(tcp_offset),
                                {6U, 0U, 1U, 4U, 0U, 0U, 0U, 0U});
                extended[ip_offset + 6U] = 60U; // Destination options, followed by TCP.
                packet::wire::write_u16(extended, ip_offset + 4U, 32U);
                const auto extension = net::PacketReceiver::parse(extended);
                assert(extension.valid());
                assert(net::tcp_response_bytes(extension) == bytes);
                extended.insert(extended.begin() + 12, {0x81U, 0U, 0U, 7U});
                extended.insert(extended.end(), 16U, 0xa5U);
                const auto combined = net::PacketReceiver::parse(extended);
                assert(combined.valid());
                assert(net::tcp_response_bytes(combined) == bytes);
            }
        }
    }
}

void test_tcp_reply_correlation()
{
    using namespace skan;
    for (const bool ipv6 : {false, true}) {
        portscan::PortSubmission submission;
        submission.probe = portscan::ScanProbeType::TcpAck;
        submission.source_ip = *core::parse_ip_address(ipv6 ? "2001:db8::1" : "192.0.2.1");
        submission.target_ip = *core::parse_ip_address(ipv6 ? "2001:db8::2" : "192.0.2.2");
        submission.source_port = 40009U;
        submission.port = {80U, portscan::Protocol::Tcp};
        submission.sequence_number = 123U;
        submission.acknowledgment_number = 456U;
        net::PacketObservation reply;
        reply.status = net::ParseStatus::Valid;
        if (ipv6) {
            reply.ipv6.emplace();
            reply.ipv6->set_next_header(6U);
            reply.ipv6->set_source_address(submission.target_ip.bytes);
            reply.ipv6->set_destination_address(submission.source_ip.bytes);
        } else {
            reply.ipv4.emplace();
            reply.ipv4->set_protocol(6U);
            reply.ipv4->set_source_address(0xc0000202U);
            reply.ipv4->set_destination_address(0xc0000201U);
        }
        reply.tcp.emplace();
        reply.tcp->set_source_port(80U);
        reply.tcp->set_destination_port(40009U);
        reply.tcp->set_sequence_number(456U);
        reply.tcp->set_flags(static_cast<std::uint16_t>(packet::TcpFlag::Rst));
        assert(net::matches_tcp_reply(submission, reply));
        // RFC 9293: without ACK set, the acknowledgment field is not significant.
        reply.tcp->set_acknowledgment_number(999U);
        assert(net::matches_tcp_reply(submission, reply));

        auto invalid = reply;
        invalid.status = net::ParseStatus::MalformedTCP;
        assert(!net::matches_tcp_reply(submission, invalid));
        invalid = reply;
        invalid.tcp.reset();
        assert(!net::matches_tcp_reply(submission, invalid));
        invalid = reply;
        invalid.tcp->set_sequence_number(457U);
        assert(!net::matches_tcp_reply(submission, invalid));
        invalid = reply;
        invalid.tcp->set_source_port(81U);
        assert(!net::matches_tcp_reply(submission, invalid));
        invalid = reply;
        invalid.tcp->set_destination_port(40010U);
        assert(!net::matches_tcp_reply(submission, invalid));
        for (const auto flag : {packet::TcpFlag::Ack, packet::TcpFlag::Syn, packet::TcpFlag::Fin}) {
            invalid = reply;
            invalid.tcp->set_flags(packet::TcpFlag::Rst | flag);
            assert(!net::matches_tcp_reply(submission, invalid));
        }
        invalid = reply;
        invalid.tcp->set_flags(packet::TcpFlag::Syn | packet::TcpFlag::Ack);
        assert(!net::matches_tcp_reply(submission, invalid));
        invalid = reply;
        if (ipv6) {
            invalid.ipv6->set_destination_address(submission.target_ip.bytes);
        } else {
            invalid.ipv4->set_destination_address(0xc0000203U);
        }
        assert(!net::matches_tcp_reply(submission, invalid));
        invalid = reply;
        if (ipv6) {
            invalid.ipv6->set_source_address(submission.source_ip.bytes);
        } else {
            invalid.ipv4->set_source_address(0xc0000203U);
        }
        assert(!net::matches_tcp_reply(submission, invalid));
        auto wrong_family = submission;
        wrong_family.target_ip = *core::parse_ip_address(ipv6 ? "192.0.2.2" : "2001:db8::2");
        assert(!net::matches_tcp_reply(wrong_family, reply));

        // Preserve existing bare RST and correlated SYN/ACK behavior.
        submission.probe = portscan::ScanProbeType::TcpSyn;
        reply.tcp->set_acknowledgment_number(0U);
        assert(net::matches_tcp_reply(submission, reply));
        reply.tcp->set_flags(packet::TcpFlag::Syn | packet::TcpFlag::Ack);
        reply.tcp->set_acknowledgment_number(124U);
        assert(net::matches_tcp_reply(submission, reply));
        reply.tcp->set_acknowledgment_number(125U);
        assert(!net::matches_tcp_reply(submission, reply));
        reply.tcp->set_acknowledgment_number(124U);
        reply.tcp->set_flags(static_cast<std::uint16_t>(packet::TcpFlag::Ack));
        assert(!net::matches_tcp_reply(submission, reply));
        submission.probe = portscan::ScanProbeType::TcpConnect;
        assert(!net::matches_tcp_reply(submission, reply));
    }
}

void test_icmp_quote_correlation()
{
    using namespace skan;
    for (const bool ipv6 : {false, true}) {
        portscan::PortSubmission submission;
        submission.probe = portscan::ScanProbeType::TcpAck;
        submission.source_ip = *core::parse_ip_address(ipv6 ? "2001:db8::1" : "192.0.2.1");
        submission.target_ip = *core::parse_ip_address(ipv6 ? "2001:db8::2" : "192.0.2.2");
        packet::TCP tcp;
        tcp.set_source_port(40009U);
        tcp.set_destination_port(80U);
        tcp.set_sequence_number(123U);
        tcp.set_acknowledgment_number(456U);
        tcp.set_flags(static_cast<std::uint16_t>(packet::TcpFlag::Ack));
        submission.packet.resize(tcp.serialized_size());
        assert(tcp.serialize(submission.packet) == core::StatusCode::Ok);
        const std::size_t header_size = ipv6 ? 40U : 20U;
        std::vector<std::uint8_t> quote(header_size + submission.packet.size());
        net::PacketObservation error;
        error.status = net::ParseStatus::Valid;
        if (ipv6) {
            packet::IPv6 original;
            original.set_next_header(6U);
            original.set_payload_length(20U);
            original.set_source_address(submission.source_ip.bytes);
            original.set_destination_address(submission.target_ip.bytes);
            assert(original.serialize(quote) == core::StatusCode::Ok);
            error.ipv6.emplace();
            error.ipv6->set_destination_address(submission.source_ip.bytes);
            error.icmpv6.emplace(packet::Icmpv6Type::DestinationUnreachable);
        } else {
            packet::IPv4 original;
            original.set_protocol(6U);
            original.set_total_length(40U);
            original.set_source_address(0xc0000201U);
            original.set_destination_address(0xc0000202U);
            assert(original.serialize(quote) == core::StatusCode::Ok);
            error.ipv4.emplace();
            error.ipv4->set_destination_address(0xc0000201U);
            error.icmp.emplace(packet::IcmpType::DestinationUnreachable);
        }
        std::copy(submission.packet.begin(), submission.packet.end(), quote.begin() + header_size);
        const auto set_quote = [ipv6](net::PacketObservation &observation, std::vector<std::uint8_t> bytes) {
            if (ipv6) { observation.icmpv6->set_payload(std::move(bytes)); }
            else { observation.icmp->set_payload(std::move(bytes)); }
        };
        // Routers can originate the outer packet: only the destination is our endpoint.
        for (std::size_t length = 8U; length <= 20U; ++length) {
            auto truncated = quote;
            truncated.resize(header_size + length);
            set_quote(error, truncated);
            assert(net::matches_tcp_unreachable(submission, error));
        }
        set_quote(error, quote);

        if (ipv6) {
            auto classified = error;
            classified.icmpv6->set_code(0U);
            assert(net::classify_tcp_unreachable_reason(classified) ==
                   portscan::ScanReason::IcmpNetworkUnreachable);
            classified.icmpv6->set_code(1U);
            assert(net::classify_tcp_unreachable_reason(classified) ==
                   portscan::ScanReason::IcmpAdministrativelyProhibited);
            classified.icmpv6->set_code(4U);
            assert(net::classify_tcp_unreachable_reason(classified) ==
                   portscan::ScanReason::IcmpPortUnreachable);
            classified.icmpv6->set_code(7U);
            assert(!net::classify_tcp_unreachable_reason(classified).has_value());
        } else {
            auto classified = error;
            classified.icmp->set_code(0U);
            assert(net::classify_tcp_unreachable_reason(classified) ==
                   portscan::ScanReason::IcmpNetworkUnreachable);
            classified.icmp->set_code(2U);
            assert(net::classify_tcp_unreachable_reason(classified) ==
                   portscan::ScanReason::IcmpProtocolUnreachable);
            classified.icmp->set_code(3U);
            assert(net::classify_tcp_unreachable_reason(classified) ==
                   portscan::ScanReason::IcmpPortUnreachable);
            classified.icmp->set_code(13U);
            assert(net::classify_tcp_unreachable_reason(classified) ==
                   portscan::ScanReason::IcmpAdministrativelyProhibited);
            classified.icmp->set_code(8U);
            assert(!net::classify_tcp_unreachable_reason(classified).has_value());
        }

        auto invalid = error;
        if (ipv6) { invalid.ipv6->set_destination_address(submission.target_ip.bytes); }
        else { invalid.ipv4->set_destination_address(0xc0000203U); }
        assert(!net::matches_tcp_unreachable(submission, invalid));
        invalid = error;
        invalid.status = net::ParseStatus::MalformedICMP;
        assert(!net::matches_tcp_unreachable(submission, invalid));
        invalid = error;
        if (ipv6) { invalid.icmpv6->set_code(255U); }
        else { invalid.icmp->set_code(255U); }
        assert(!net::matches_tcp_unreachable(submission, invalid));
        auto truncated = quote;
        truncated.resize(header_size + 7U);
        set_quote(invalid = error, truncated);
        assert(!net::matches_tcp_unreachable(submission, invalid));
        // Both ports, sequence, ACK identity, and flags must agree when quoted.
        for (const std::size_t offset : {0U, 2U, 4U, 8U, 13U}) {
            auto changed = quote;
            changed[header_size + offset] ^= 1U;
            set_quote(invalid = error, changed);
            assert(!net::matches_tcp_unreachable(submission, invalid));
        }
        auto wrong_endpoint = submission;
        wrong_endpoint.target_ip.bytes[0] ^= 1U;
        assert(!net::matches_tcp_unreachable(wrong_endpoint, error));
        wrong_endpoint = submission;
        wrong_endpoint.source_ip.bytes[0] ^= 1U;
        assert(!net::matches_tcp_unreachable(wrong_endpoint, error));
        auto changed = quote;
        changed[0] = 0U;
        set_quote(invalid = error, changed);
        assert(!net::matches_tcp_unreachable(submission, invalid));
        if (!ipv6) {
            changed = quote;
            changed[10] ^= 1U; // Invalid quoted IPv4 checksum.
            set_quote(invalid = error, changed);
            assert(!net::matches_tcp_unreachable(submission, invalid));
        }
    }
}

} // namespace

int main()
{
    test_captured_open_and_closed_syn_responses();
    test_tcp_response_preserves_valid_wire_options();
    test_tcp_reply_correlation();
    test_icmp_quote_correlation();
    skan::io::IOEngine io_engine;
    assert(io_engine.initialization_status() == skan::core::StatusCode::Ok);

    skan::net::LinuxNetworkScanTransport invalid(
        io_engine, skan::net::NetworkScanConfig{});
    assert(!invalid.supports(skan::portscan::ScanProbeType::TcpSyn));
    assert(invalid.open().status == skan::net::NetworkScanStatus::InvalidConfiguration);

    if (!skan::net::find_interface("lo").has_value()) {
        std::cout << "SKIPPED: loopback interface unavailable\n";
        return 0;
    }
    skan::net::LinuxNetworkScanTransport transport(
        io_engine, skan::net::NetworkScanConfig{"lo", 65535U, true, std::nullopt});
    const skan::net::NetworkScanResult opened = transport.open();
    if (!opened.success()) {
        assert(opened.category != skan::net::PreflightCategory::Ready);
        assert(opened.family == skan::core::AddressFamily::IPv4 || opened.family == skan::core::AddressFamily::IPv6);
        assert(!opened.message.empty());
        std::cout << "SKIPPED: Linux network scan transport unavailable: " << opened.message << '\n';
        return 0;
    }
    assert(transport.is_open());
    assert(transport.supports(skan::portscan::ScanProbeType::TcpSyn));
    assert(transport.supports(skan::portscan::ScanProbeType::TcpAck));
    assert(transport.session().active);
    assert(transport.session().id != 0U);
    assert(transport.capture_file_descriptor() >= 0);
    assert(transport.transport_file_descriptor() >= 0);
    transport.close();
    transport.close();
    assert(!transport.is_open());
    assert(!transport.supports(skan::portscan::ScanProbeType::TcpSyn));
    assert(!transport.supports(skan::portscan::ScanProbeType::TcpAck));
    return 0;
}
